apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
spec:
  selector:
    type: {{ .Values.labelType }}
  ports:
    - name: http
      port: {{ .Values.container.port }}
      nodePort: {{ .Values.container.nodePort }}
  type: {{ .Values.container.type }}
