apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
data:
  RABBIT_HOST: "{{ .Values.rabbit.host }}"
  RABBIT_TIMEOUT: "{{ .Values.rabbit.timeout }}"
  RABBIT_EXCHANGE_NAME: "{{ .Values.rabbit.exchange }}"
  RABBIT_QUEUE_NAME: "{{ .Values.rabbit.queue }}"
